ifndef MK_VARS_PY
MK_VARS_PY=1

# If we have credentials, make them available to targets
ifdef POETRY_USERNAME
POETRY_HTTP_BASIC_OTC_USERNAME = $(POETRY_USERNAME)
POETRY_HTTP_BASIC_OTC_PASSWORD = $(POETRY_PASSWORD)
endif

ifdef POETRY_HTTP_BASIC_OTC_USERNAME
export POETRY_HTTP_BASIC_OTC_USERNAME
export POETRY_HTTP_BASIC_OTC_PASSWORD
endif

endif
